"""The free single-lookup page and the JSON endpoint behind it.

The page is server-rendered rather than a client-side app for one reason: a result that only exists
after JavaScript runs is not a page a crawler indexes or a broker can paste into an email. Every
lookup has a shareable `/?q=` URL that renders its own answer.
"""
import html
import json
import os
import re
from contextlib import asynccontextmanager
from pathlib import Path
from urllib.parse import quote

from fastapi import Body, FastAPI, HTTPException, Query
from fastapi.responses import FileResponse, HTMLResponse, PlainTextResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from qdrant_client import QdrantClient
from starlette.concurrency import run_in_threadpool

from classify import ANSWER_CONFIDENCE_THRESHOLD, RETRIEVAL_TOP_K, Classification, classify, default_chat_client
from cross import RULINGS_FILE, load_rulings
from retrieve import COLLECTION, ENCODER_VERSION, get, index, relevant, search

STATIC = Path(__file__).resolve().parent / "static"
TEMPLATE = STATIC / "index.html"
RULING_TEMPLATE = STATIC / "ruling.html"
CROSS_URL = "https://rulings.cbp.gov/ruling/"
# Absolute URLs are required in a sitemap and in a canonical tag, and getting them wrong is how a
# site tells Google that 23,929 pages are really one page on localhost.
BASE_URL = os.getenv("BASE_URL", "http://localhost:8099").rstrip("/")
RELATED_RULINGS = 6
# Shown against every code the tool produces, answered or withheld. Adjacent to the number rather
# than in the footer: a disclaimer nobody scrolls to is one nobody read.
DISCLAIMER = (
    "Generated by an AI model and <strong>can be wrong</strong>. This is not customs advice and not a "
    "binding ruling. The importer of record remains responsible for what is declared to CBP - have a "
    "licensed customs broker confirm the classification before you file."
)
MINIMUM_QUERY_CHARACTERS = 12
MAXIMUM_QUERY_CHARACTERS = 4000
# Embedded Qdrant by default so a checkout runs with nothing installed; point QDRANT_URL at a
# server once the corpus outgrows embedded mode, which warns above roughly 20k points.
QDRANT_URL = os.getenv("QDRANT_URL", "")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY", "") or None
QDRANT_PATH = Path(__file__).resolve().parent / "data" / "qdrant"
# Both live outside the storage directory so Qdrant never sees a file it did not write.
SEED_STAMP = QDRANT_PATH.with_suffix(".seed")
SITEMAP_FILE = QDRANT_PATH.with_suffix(".sitemap.xml")
# sitemaps.org caps one sitemap at 50,000 URLs, so past that the corpus is split and /sitemap.xml
# becomes an index pointing at the parts. A single file over the cap is rejected outright.
SITEMAP_URLS_PER_FILE = 50_000
SUGGEST_MINIMUM_CHARACTERS = 3
SUGGEST_RESULTS = 5

state: dict = {}


def corpus_stamp() -> str:
    """Fingerprint the corpus file, so a rebuild is triggered by a changed file and nothing else.

    Size and modification time rather than a content hash: the corpus is 140MB, and reading all of
    it to decide whether to read all of it is the cost the stamp exists to avoid. The encoder version
    rides along so that changing how text is vectorised also forces the rebuild it requires.
    """
    stat = RULINGS_FILE.stat()
    return f"v{ENCODER_VERSION}:{stat.st_size}:{stat.st_mtime_ns}"


def seed(client: QdrantClient) -> int:
    """Index the corpus, or reuse the stored index when the corpus has not changed since it was built.

    Nothing here touches `rulings.jsonl` on the reuse path - not to index, not to build the sitemap,
    not to serve a ruling page. That file is now approaching a gigabyte, and parsing it was the whole
    of startup once vectorising was cached. The collection is dropped before a rebuild: upserts alone
    would leave points for rulings that have since been deleted from the corpus.
    """
    indexed = COLLECTION in {c.name for c in client.get_collections().collections}
    # A remote index is seeded out of band by `python seed_cloud.py`, not by a web process: the
    # corpus file is not deployed with the app, and a serverless start has neither the disk for it
    # nor the minutes. What is already in the cluster is what gets served.
    if QDRANT_URL and indexed:
        return client.count(collection_name=COLLECTION).count
    stored = SEED_STAMP.read_text().strip() if SEED_STAMP.exists() else ""
    if stored == corpus_stamp() and indexed and SITEMAP_FILE.exists():
        return client.count(collection_name=COLLECTION).count
    if indexed:
        client.delete_collection(COLLECTION)
    rulings = load_rulings(RULINGS_FILE)
    written = index(client, rulings)
    build_sitemap(rulings)
    # Written last, so a crash part-way through indexing reseeds on the next start rather than
    # trusting a half-built index.
    SEED_STAMP.write_text(corpus_stamp())
    # Count rather than trust the write total: CROSS reissues a handful of ruling numbers, and those
    # collapse onto one point, so a fresh index and a reused one must not report different sizes.
    return client.count(collection_name=COLLECTION).count


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Open the index once. An unchanged corpus is neither parsed nor re-vectorised on a restart."""
    client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY) if QDRANT_URL else QdrantClient(path=str(QDRANT_PATH))
    state["client"] = client
    state["indexed"] = seed(client)
    state["chat"] = default_chat_client()
    yield
    state.clear()


app = FastAPI(title="HS classification", lifespan=lifespan)
app.mount("/static", StaticFiles(directory=STATIC), name="static")


class LookupRequest(BaseModel):
    """A merchandise description to classify."""

    description: str = Field(min_length=MINIMUM_QUERY_CHARACTERS, max_length=MAXIMUM_QUERY_CHARACTERS)


def lookup(description: str) -> Classification:
    """Classify one description against the loaded corpus."""
    return classify(description.strip(), client=state["client"], chat=state["chat"])


def product_name(subject: str) -> str:
    """The article a ruling is about, as a shopper would say it.

    CBP subject lines are all shaped "The tariff classification of X from Country", some with an
    origin or NAFTA clause wedged in. Stripping the boilerplate leaves X, which is what the side
    panel offers as a neighbouring product to classify.
    """
    prefix = r"^(the\s+)?(tariff\s+)?classification\s*,?\s*(and\s+(the\s+)?(country\s+of\s+origin|status\s+under\s+.*?)\s*,?\s*)?of\s+"
    name = re.sub(prefix, "", subject.strip(), flags=re.I)
    # \s* rather than \s+ after "from": the corpus carries typos like "a cloth bag fromGuatemala".
    return re.sub(r"[,\s]+from\s*[^,]+$", "", name).strip(" .,")


def candidate(hit) -> dict:
    """One neighbouring article for the side panel: what to show, and what to classify if clicked.

    A name too short to re-submit is still worth showing - it is the subject line behind it that
    gets sent, so every row in the panel stays clickable.
    """
    product = product_name(hit.subject)[:90]
    return {
        "hs6": hit.hs6,
        "product": product,
        "query": product if len(product) >= MINIMUM_QUERY_CHARACTERS else hit.subject.strip(" .,"),
    }


def render_rulings(hits: list, cited: set[str]) -> str:
    """Render retrieved rulings as table rows, marking the ones the answer actually leaned on."""
    return "".join(
        f"""<tr class="{'cited' if hit.ruling_number in cited else ''}">
          <td class="rn"><a href="/ruling/{html.escape(hit.ruling_number)}">{html.escape(hit.ruling_number)}</a></td>
          <td class="hs">{html.escape(hit.hs6)}</td>
          <td class="subject">{html.escape(hit.subject)}</td>
          <td class="date">{html.escape(hit.date)}</td>
          <td class="tag">{'Cited' if hit.ruling_number in cited else 'Consulted'}</td>
        </tr>"""
        for hit in hits
    )


def render_too_short(query: str) -> str:
    """Answer a too-short query with what the corpus holds for it, rather than an instruction.

    A brand or a bare noun is the common case here, and it is not classifiable: CBP classifies on
    what an article is made of and what it does, so one brand spans many chapters. Showing that
    spread is the useful reply - it is the evidence for why more detail is needed, and it costs a
    retrieval rather than a model call.
    """
    hits = search(query, top_k=SUGGEST_RESULTS, client=state["client"]) if len(query) >= SUGGEST_MINIMUM_CHARACTERS else []
    # The claim below is about rulings that contain the term, so only those may be counted or shown.
    hits = relevant(query, hits)
    chapters = {hit.hs6[:2] for hit in hits}
    spread = (
        f"""<p>In the indexed rulings that term already spans {len(chapters)} different chapters.
        A brand name is not a classification: CBP classifies on what the article is made of and what
        it does, so the same brand appears under toys, apparel, stationery and jewellery.</p>"""
        if len(chapters) > 1 else ""
    )
    table = (
        f"""<h2>Rulings matching that term</h2>
        <table class="rulings">
          <thead><tr><th>Ruling</th><th>HS6</th><th>Subject</th><th>Date</th><th>Use</th></tr></thead>
          <tbody>{render_rulings(hits, set())}</tbody>
        </table>"""
        if hits else ""
    )
    return f"""<section class="result">
      <p class="verdict escalated">More detail needed</p>
      <p class="note">Not enough to classify.</p>
      <div class="withheld-box">
        {spread}
        <p>Describe the goods in a sentence or two: what the article <strong>is</strong>, what it is
        <strong>made of</strong>, what it is <strong>used for</strong>, and whether it is finished or
        imported for further manufacture. "A plastic construction toy of moulded ABS interlocking
        bricks, boxed for retail sale, for ages 6 and up" classifies; a brand name cannot.</p>
      </div>
      {table}
    </section>"""


def render_result(result: Classification) -> str:
    """Render the gate's verdict as the headline, because the verdict is what is being sold.

    An escalation is presented as a result rather than as a failure: it gets the same stage as an
    answer - an em dash where the code would be, at the same size - and the rulings that were
    consulted are still shown, so a withheld answer leaves the user better off than they started.
    """
    if result.disposition == "answered":
        headline = f"""<p class="verdict answered">Classified</p>
        <p class="code">{html.escape(result.hs6 or "")}</p>
        <p class="note">{html.escape(result.reason)}</p>"""
    else:
        headline = f"""<p class="verdict escalated">Not answered</p>
        <p class="nocode">WITHHELD</p>
        <p class="note">Classification withheld.</p>
        <div class="withheld-box">
          <p>{html.escape(result.reason)}</p>
          <p>A classification below the {ANSWER_CONFIDENCE_THRESHOLD:.0%} threshold is withheld rather
          than guessed: a wrong HS code on an entry is a false statement to CBP under
          19&nbsp;U.S.C.&nbsp;&sect;1592, and the penalty follows the importer of record.</p>
          <p>This is not an error. The rulings below may still help you narrow the question, and a
          licensed customs broker can make the call.</p>
        </div>"""
    rows = render_rulings(result.candidates, set(result.citations))
    return f"""<section class="result">
      {headline}
      <p class="confidence">{result.confidence:.0%}<span>Confidence</span></p>
      <p class="disclaimer"><span>AI-generated</span>{DISCLAIMER}</p>
      <h2>Reasoning</h2>
      <p class="reasoning">{html.escape(result.reasoning)}</p>
      <h2>CBP rulings consulted</h2>
      <table class="rulings">
        <thead><tr><th>Ruling</th><th>HS6</th><th>Subject</th><th>Date</th><th>Use</th></tr></thead>
        <tbody>{rows}</tbody>
      </table>
    </section>"""


def sse(payload: dict) -> str:
    """One server-sent event. Kept next to the endpoint so the wire format has a single spelling."""
    return f"data: {json.dumps(payload)}\n\n"


def render_page(query: str, body: str) -> str:
    """Substitute the query and rendered result into the static template.

    The canonical URL deliberately omits `q`: every distinct lookup would otherwise be a separate
    indexable page saying roughly the same thing, which is how a useful tool turns into thin content.
    """
    return (
        TEMPLATE.read_text(encoding="utf-8")
        .replace("{{CANONICAL}}", f"{BASE_URL}/")
        .replace("{{COUNT}}", f"{state.get('indexed', 0):,}")
        .replace("{{QUERY}}", html.escape(query, quote=True))
        .replace("<!--RESULT-->", body)
    )


def sitemap_part(number: int) -> Path:
    """The path of one sitemap part, named so the route and the writer cannot disagree."""
    return QDRANT_PATH.with_suffix(f".sitemap-{number}.xml")


def build_sitemap(rulings: list) -> int:
    """Write the corpus as a sitemap index plus its parts, returning how many parts were written.

    These pages are only discoverable through this file, and a sitemap over the 50,000-URL cap is
    rejected whole rather than truncated - so the corpus is chunked and /sitemap.xml addresses the
    parts. The index is written last: a crawler that reads it must not find a part still missing.
    """
    urls = [f"<url><loc>{BASE_URL}/</loc></url>"] + [
        f"<url><loc>{BASE_URL}/ruling/{quote(ruling.ruling_number)}</loc><lastmod>{ruling.date}</lastmod></url>"
        for ruling in rulings
    ]
    chunks = [urls[start:start + SITEMAP_URLS_PER_FILE] for start in range(0, len(urls), SITEMAP_URLS_PER_FILE)] or [[]]

    # A corpus that shrank leaves parts the new index does not name; unreferenced, they would still
    # be served and crawled.
    for stale in QDRANT_PATH.parent.glob(f"{QDRANT_PATH.name}.sitemap-*.xml"):
        stale.unlink()

    for number, chunk in enumerate(chunks):
        sitemap_part(number).write_text(
            f'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">{"".join(chunk)}</urlset>',
            encoding="utf-8",
        )
    parts = "".join(f"<sitemap><loc>{BASE_URL}/sitemap-{number}.xml</loc></sitemap>" for number in range(len(chunks)))
    SITEMAP_FILE.write_text(
        f'<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">{parts}</sitemapindex>',
        encoding="utf-8",
    )
    return len(chunks)


def render_ruling(ruling) -> str:
    """Render one ruling as an indexable page, linked to the rulings nearest it in the corpus.

    The related list is the point as much as the ruling text is: 23,929 orphan pages are 23,929
    pages nothing links to, and retrieval already knows which ones belong next to each other.
    """
    related = [hit for hit in search(ruling.description, top_k=RELATED_RULINGS + 1, client=state["client"]) if hit.ruling_number != ruling.ruling_number]
    codes = "".join(
        f'<li><span class="hs6">{html.escape(code[:6])}</span>{html.escape(code[6:])}</li>' for code in ruling.hts_codes
    )
    related_items = "".join(
        f'<li><a href="/ruling/{html.escape(hit.ruling_number)}">{html.escape(hit.subject)}</a><span class="hs">{html.escape(hit.hs6)}</span></li>'
        for hit in related[:RELATED_RULINGS]
    )
    summary = " ".join(ruling.description.split())[:155]
    return (
        RULING_TEMPLATE.read_text(encoding="utf-8")
        .replace("{{TITLE}}", html.escape(f"{ruling.subject} - CBP ruling {ruling.ruling_number} (HS {ruling.hs6})"))
        .replace("{{META}}", html.escape(f"HS {ruling.hs6}. {summary}", quote=True))
        .replace("{{CANONICAL}}", f"{BASE_URL}/ruling/{quote(ruling.ruling_number)}")
        .replace("{{SUBJECT}}", html.escape(ruling.subject))
        .replace("{{CODES}}", codes)
        .replace("{{DATE}}", html.escape(ruling.date))
        .replace("{{DESCRIPTION}}", html.escape(ruling.description))
        .replace("{{RELATED}}", related_items or "<li>No related rulings were found.</li>")
        .replace("{{QUERY}}", quote(ruling.subject))
        .replace("{{NUMBER}}", html.escape(ruling.ruling_number))
    )


@app.get("/", response_class=HTMLResponse)
def home(q: str = Query(default="", max_length=MAXIMUM_QUERY_CHARACTERS)) -> HTMLResponse:
    """Render the lookup form, and the result for `q` when one was asked for."""
    query = q.strip()
    if not query:
        return HTMLResponse(render_page("", ""))
    if len(query) < MINIMUM_QUERY_CHARACTERS:
        return HTMLResponse(render_page(query, render_too_short(query)))
    return HTMLResponse(render_page(query, render_result(lookup(query))))


@app.get("/api/lookup/stream")
async def lookup_stream(q: str = Query(default="", max_length=MAXIMUM_QUERY_CHARACTERS)) -> StreamingResponse:
    """Stream a lookup as its two real stages, so the wait shows what is being waited on.

    Retrieval over the local index is quick; the model call is the wait. Both numbers reported here
    are measured rather than scripted - `scanned` is the indexed corpus and `candidates` is what
    retrieval actually returned - because a progress bar that invents its numbers is a lie the user
    cannot check. The final event carries the same HTML the server-rendered page would have shown,
    so there is one renderer and `/?q=` keeps working with JavaScript off.
    """
    query = q.strip()

    async def stages():
        if len(query) < MINIMUM_QUERY_CHARACTERS:
            body = render_too_short(query) if query else ""
            yield sse({"stage": "done", "html": body})
            return
        yield sse({"stage": "search", "scanned": state.get("indexed", 0)})
        # Filtered here rather than inside classify, because the count reported below has to be the
        # shortlist the model is actually given.
        found = await run_in_threadpool(search, query, top_k=RETRIEVAL_TOP_K, client=state["client"])
        hits = relevant(query, found)
        # The candidates ride along so the wait can show the codes actually under consideration
        # rather than a decorative spinner. They are shortlisted, not answers, and the panel
        # showing them is replaced by the graded verdict.
        yield sse({
            "stage": "grade",
            "candidates": [candidate(hit) for hit in hits],
        })
        result = await run_in_threadpool(
            classify, query, client=state["client"], chat=state["chat"], hits=hits
        )
        yield sse({"stage": "done", "html": render_result(result)})

    # no-transform and X-Accel-Buffering stop a proxy from holding the stages back to deliver them
    # as one blob, which would leave the bar frozen for the whole lookup.
    return StreamingResponse(
        stages(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache, no-transform", "X-Accel-Buffering": "no"},
    )


@app.post("/api/classify")
def api_classify(request: LookupRequest = Body(...)) -> Classification:
    """Classify one description and return the full result, gate verdict included."""
    return lookup(request.description)


@app.get("/api/suggest")
def suggest(q: str = Query(default="", max_length=MAXIMUM_QUERY_CHARACTERS)) -> list[dict]:
    """Rulings that already look like what is being typed, for the live panel on the home page.

    Retrieval only - no model call - so this is free to fire on every keystroke and can never
    produce a classification. It shows what the corpus has, not what the answer is.
    """
    query = q.strip()
    if len(query) < SUGGEST_MINIMUM_CHARACTERS:
        return []
    return [
        {"ruling_number": hit.ruling_number, "hs6": hit.hs6, "subject": hit.subject}
        for hit in relevant(query, search(query, top_k=SUGGEST_RESULTS, client=state["client"]))
    ]


@app.get("/api/health")
def health() -> dict:
    """Report whether the corpus is loaded and whether a model is configured."""
    return {"indexed_rulings": state.get("indexed", 0), "model": bool(state.get("chat")), "threshold": ANSWER_CONFIDENCE_THRESHOLD}


@app.get("/ruling/{number}", response_class=HTMLResponse)
def ruling_page(number: str) -> HTMLResponse:
    """Render one CBP ruling as its own indexable page."""
    ruling = get(number, client=state["client"])
    if ruling is None:
        raise HTTPException(status_code=404, detail="No such ruling in the corpus.")
    return HTMLResponse(render_ruling(ruling))


@app.get("/sitemap.xml")
def sitemap() -> FileResponse:
    """Serve the sitemap index, written to disk when the corpus was last indexed."""
    if not SITEMAP_FILE.exists():
        raise HTTPException(status_code=404, detail="No sitemap: this instance serves a remote index.")
    return FileResponse(SITEMAP_FILE, media_type="application/xml")


@app.get("/sitemap-{number}.xml")
def sitemap_chunk(number: int) -> FileResponse:
    """Serve one part of the sitemap. `number` is an int, so it cannot address another file."""
    path = sitemap_part(number)
    if not path.exists():
        raise HTTPException(status_code=404, detail="No such sitemap.")
    return FileResponse(path, media_type="application/xml")


@app.get("/robots.txt", response_class=PlainTextResponse)
def robots() -> str:
    """Allow the corpus to be crawled, and keep lookup results out of the index."""
    return f"User-agent: *\nAllow: /\nDisallow: /?q=\nDisallow: /api/\nSitemap: {BASE_URL}/sitemap.xml\n"
